### ISSUE TITLE
IOS: Why saveToGallery = true logic 

### ISSUE THREAD

**Issue by adnanakbar** [triniwiz/nativescript-videorecorder#33]
I am curious why when saveToGallery  = true, the file path is not return? It would be really handy to get the path of the file saved to gallery. This plugin returning the the path when saveToGallery = false which is of no use because the file is removed. It feels like this logic should be placed other way around. Please let me know if I didn't understand this correctly. 
Basically I need to save it to library and then use the path for further processing...

**Comment by triniwiz** [comment]
It returns the path now

**Comment by sylwesterdigital** [comment]
It returns:
```
/asset.MOV 
```
When I try to record again recordVideo, `videorecorder.record().then((data) => does nothing`

So I try to work only with option: saveToGallery: false. The problem is that videos are temporarily saved to this folder:
```
/private/var/mobile/Containers/Data/Application/62A11037-C89A-47C6-AFBB-BF1CB260AA05/tmp
```

When I close and reopen app I do not know how to list this folder. Are these tmp videos erased?
The only solution I worked out is to upload them earlier to the server...

I really would love you could finish this plugin as soon as possible, please ;)
